"use client";

import { useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import type { SessionDetail, ArtifactOut } from "@/lib/api";
import Toast, { useToast } from "@/components/Toast";

const ARTIFACT_META: Record<string, { icon: string; color: string; accent: string; border: string }> = {
  founder_synthesis: {
    icon: "💡",
    color: "text-orange-400",
    accent: "bg-orange-500/10",
    border: "border-orange-500/30",
  },
  market_analysis: {
    icon: "📊",
    color: "text-sky-400",
    accent: "bg-sky-500/10",
    border: "border-sky-500/30",
  },
  product_spec: {
    icon: "🎯",
    color: "text-emerald-400",
    accent: "bg-emerald-500/10",
    border: "border-emerald-500/30",
  },
  gtm_strategy: {
    icon: "🚀",
    color: "text-cyan-400",
    accent: "bg-cyan-500/10",
    border: "border-cyan-500/30",
  },
  financial_model: {
    icon: "📈",
    color: "text-lime-400",
    accent: "bg-lime-500/10",
    border: "border-lime-500/30",
  },
  tech_blueprint: {
    icon: "🏗️",
    color: "text-violet-400",
    accent: "bg-violet-500/10",
    border: "border-violet-500/30",
  },
  legal_assessment: {
    icon: "⚖️",
    color: "text-red-400",
    accent: "bg-red-500/10",
    border: "border-red-500/30",
  },
  vc_review: {
    icon: "💰",
    color: "text-amber-400",
    accent: "bg-amber-500/10",
    border: "border-amber-500/30",
  },
};

const ARTIFACT_ORDER = [
  "founder_synthesis",
  "market_analysis",
  "product_spec",
  "gtm_strategy",
  "financial_model",
  "tech_blueprint",
  "legal_assessment",
  "vc_review",
];

export default function OutputClient({ session }: { session: SessionDetail }) {
  const [activeKey, setActiveKey] = useState(ARTIFACT_ORDER[0]);
  const [copiedKey, setCopiedKey] = useState<string | null>(null);
  const { toast, show: showToast } = useToast();

  const artifactMap = Object.fromEntries(session.artifacts.map((a) => [a.key, a]));
  const orderedArtifacts = ARTIFACT_ORDER.map((k) => artifactMap[k]).filter(Boolean);
  const active = artifactMap[activeKey];
  const meta = active ? ARTIFACT_META[active.key] : null;

  const handleShare = async () => {
    const shareUrl = `${window.location.origin}/s/${session.share_slug}`;
    try {
      await navigator.clipboard.writeText(shareUrl);
      showToast("Link copied to clipboard!", "success");
    } catch {
      // Fallback for browsers that block clipboard
      const input = document.createElement("input");
      input.value = shareUrl;
      document.body.appendChild(input);
      input.select();
      document.execCommand("copy");
      document.body.removeChild(input);
      showToast("Link copied to clipboard!", "success");
    }
  };

  const handleCopyArtifact = async (content: string, key: string) => {
    await navigator.clipboard.writeText(content);
    setCopiedKey(key);
    showToast("Copied to clipboard!", "success");
    setTimeout(() => setCopiedKey(null), 2000);
  };

  const handleDownload = () => {
    const all = orderedArtifacts.map((a) => `# ${a.title}\n\n${a.content}`).join("\n\n---\n\n");
    const blob = new Blob(
      [`# AI Startup Studio — ${session.idea}\n\nGenerated by AI Startup Studio\n\n---\n\n${all}`],
      { type: "text/markdown" }
    );
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "startup-package.md";
    a.click();
    URL.revokeObjectURL(url);
    showToast("Downloaded!", "success");
  };

  return (
    <div className="min-h-screen bg-surface">
      <Toast message={toast?.message ?? ""} show={!!toast} type={toast?.type} />

      {/* Header */}
      <header className="border-b border-surface-border px-6 py-4 sticky top-0 z-40 bg-surface/95 backdrop-blur">
        <div className="max-w-7xl mx-auto flex items-center justify-between gap-4">
          <div className="flex items-center gap-3 min-w-0">
            <a href="/" className="font-bold text-slate-100 shrink-0 hover:text-brand-500 transition-colors">
              🚀 AI Startup Studio
            </a>
            <span className="text-slate-700 hidden sm:block">·</span>
            <p className="text-slate-400 text-sm truncate hidden sm:block italic">{session.idea}</p>
          </div>
          <div className="flex items-center gap-2 shrink-0">
            <button
              onClick={handleShare}
              className="flex items-center gap-1.5 text-sm text-slate-300 border border-surface-border rounded-lg px-3 py-1.5 hover:bg-surface-hover hover:text-white transition-all"
            >
              <span>🔗</span> Share
            </button>
            <button
              onClick={handleDownload}
              className="flex items-center gap-1.5 text-sm text-white bg-brand-500 hover:bg-brand-600 rounded-lg px-3 py-1.5 transition-all font-medium"
            >
              <span>⬇</span> Download
            </button>
          </div>
        </div>
      </header>

      {/* Idea hero */}
      <div className="border-b border-surface-border bg-gradient-to-r from-surface-card to-surface px-6 py-6">
        <div className="max-w-7xl mx-auto">
          <p className="text-xs text-slate-500 uppercase tracking-widest mb-2">Startup idea analysed</p>
          <p className="text-xl font-semibold text-slate-100 max-w-3xl">{session.idea}</p>
          {/* Artifact count badges */}
          <div className="flex flex-wrap gap-2 mt-4">
            {orderedArtifacts.map((a) => {
              const m = ARTIFACT_META[a.key];
              return (
                <button
                  key={a.key}
                  onClick={() => setActiveKey(a.key)}
                  className={`
                    flex items-center gap-1.5 text-xs px-2.5 py-1 rounded-full border transition-all
                    ${activeKey === a.key
                      ? `${m.accent} ${m.border} ${m.color} font-medium`
                      : "bg-surface-card border-surface-border text-slate-500 hover:text-slate-300"}
                  `}
                >
                  <span>{m.icon}</span>
                  {a.title}
                </button>
              );
            })}
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-6 py-6 flex gap-6">
        {/* Sidebar */}
        <aside className="w-56 shrink-0">
          <div className="sticky top-[88px] space-y-1">
            <p className="text-xs text-slate-600 uppercase tracking-widest px-3 mb-3">Artifacts</p>
            {orderedArtifacts.map((artifact) => {
              const m = ARTIFACT_META[artifact.key];
              const isActive = activeKey === artifact.key;
              return (
                <button
                  key={artifact.key}
                  onClick={() => setActiveKey(artifact.key)}
                  className={`
                    w-full flex items-center gap-2.5 text-left px-3 py-2.5 rounded-xl text-sm transition-all
                    ${isActive
                      ? `${m.accent} ${m.border} border ${m.color} font-medium`
                      : "text-slate-400 hover:text-slate-200 hover:bg-surface-hover border border-transparent"}
                  `}
                >
                  <span className="text-base shrink-0">{m.icon}</span>
                  <span className="truncate">{artifact.title}</span>
                </button>
              );
            })}
          </div>
        </aside>

        {/* Main content */}
        <main className="flex-1 min-w-0 animate-fade-in">
          {active && meta && (
            <div className={`rounded-2xl border ${meta.border} overflow-hidden`}>
              {/* Artifact header */}
              <div className={`${meta.accent} border-b ${meta.border} px-6 py-4 flex items-center justify-between`}>
                <div className="flex items-center gap-3">
                  <span className="text-2xl">{meta.icon}</span>
                  <div>
                    <h2 className={`text-lg font-bold ${meta.color}`}>{active.title}</h2>
                    <p className="text-xs text-slate-500 mt-0.5">Generated by AI Startup Studio</p>
                  </div>
                </div>
                <button
                  onClick={() => handleCopyArtifact(active.content, active.key)}
                  className={`
                    text-xs px-3 py-1.5 rounded-lg border transition-all font-medium
                    ${copiedKey === active.key
                      ? "bg-emerald-500/20 border-emerald-500/40 text-emerald-300"
                      : `${meta.accent} ${meta.border} ${meta.color} hover:opacity-80`}
                  `}
                >
                  {copiedKey === active.key ? "✓ Copied" : "Copy"}
                </button>
              </div>

              {/* Rendered markdown */}
              <div className="bg-surface-card px-8 py-8">
                <div className="prose max-w-none">
                  <ReactMarkdown remarkPlugins={[remarkGfm]}>{active.content}</ReactMarkdown>
                </div>
              </div>
            </div>
          )}

          {/* Navigation between artifacts */}
          {active && (
            <div className="flex justify-between mt-4">
              {(() => {
                const idx = ARTIFACT_ORDER.indexOf(activeKey);
                const prev = idx > 0 ? artifactMap[ARTIFACT_ORDER[idx - 1]] : null;
                const next = idx < ARTIFACT_ORDER.length - 1 ? artifactMap[ARTIFACT_ORDER[idx + 1]] : null;
                return (
                  <>
                    <div>
                      {prev && (
                        <button
                          onClick={() => setActiveKey(prev.key)}
                          className="flex items-center gap-2 text-sm text-slate-400 hover:text-slate-200 transition-colors"
                        >
                          ← {prev.title}
                        </button>
                      )}
                    </div>
                    <div>
                      {next && (
                        <button
                          onClick={() => setActiveKey(next.key)}
                          className="flex items-center gap-2 text-sm text-slate-400 hover:text-slate-200 transition-colors"
                        >
                          {next.title} →
                        </button>
                      )}
                    </div>
                  </>
                );
              })()}
            </div>
          )}
        </main>
      </div>
    </div>
  );
}
